info:
  app:
    name: Kubernetes Cost Service
    description: Project FOR hackathon
    version: 0.0.1


spring:
  profiles:
    active: local

server:
  port: 6969

  application:
    name: kubernetes-cost-service

  flyway:
    check-location: true
    enabled: true
    url: ${POSTGRES_URL}
    user: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    testWhileIdle: true
    validationQuery: SELECT 1
    platform: postgresql
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${POSTGRES_MAX_POOL_SIZE}

    jpa:
      show-sql: false
      generate-ddl: false
      hibernate:
        ddl-auto: validate
        use-new-id-generator-mappings: false

      properties:
        hibernate:
          jdbc:
            time_zone: UTC


application:
  app-env: ${APP_ENV}
